<a href="https://colab.research.google.com/github/ramyakniranjan/Deep_learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors**

In [1]:
import torch
import numpy as np

Creating tensors:

In [3]:
# from data:
data = [[2,3],[4,5]]
xdata = torch.tensor(data)
xdata


tensor([[2, 3],
        [4, 5]])

In [6]:
# from numpy array:
np_array = np.array(data)
tensor = torch.from_numpy(np_array)
tensor

tensor([[2, 3],
        [4, 5]])

In [19]:
# from another tensor:
print(f"tensor xdata: \n  {xdata} \n")
ones_tensor = torch.ones_like(xdata)
print(f"Ones Tensor: \n {ones_tensor} \n")

zeros_tensor = torch.zeros_like(xdata)
print(f"Zeros Tensor: \n {zeros_tensor} \n")

rand_tensor = torch.rand_like(xdata, dtype=torch.float)
print(f"Random Tensor: \n {rand_tensor} \n")



tensor xdata: 
  tensor([[2, 3],
        [4, 5]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.4548, 0.8972],
        [0.4355, 0.0520]]) 



In [16]:
#With random or constant values:
shape=(2,3,)

ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4666, 0.8044, 0.3141],
        [0.5004, 0.1598, 0.8529]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# **Attributes of a tensor:**

In [42]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Data typpe of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Data typpe of a tensor: torch.float32
Device tensor is stored on: cpu


# **Operations on Tensors**

In [21]:
# Moving our tensor to GPU if available:

if torch.cuda.is_available():
  tensor = tensor.to("cuda")

**Standard numpy-like indexing and slicing:**

In [43]:
tensor = torch.ones(4,4)
print(tensor,"\n")
print(f"first row: {tensor[0]}\n")
print(f"first column: {tensor[:,0]}\n")
print(f"last row: {tensor[...,-1]}\n")
tensor[:,1]=0
print('\n',tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

first row: tensor([1., 1., 1., 1.])

first column: tensor([1., 1., 1., 1.])

last row: tensor([1., 1., 1., 1.])


 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**:

In [44]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [45]:
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


In [46]:
t2 = torch.stack([tensor,tensor,tensor],dim=0)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [47]:
t2 = torch.stack([tensor,tensor,tensor],dim=1)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


**Arithmetic operations**:

In [54]:
# matrix multiplication between two tensors. y1, y2, y3 will have the same value.
print(tensor,'\n')
print(tensor.T,'\n')
y1 = tensor @ tensor.T
print(y1,'\n')
y2 = tensor.matmul(tensor.T)
print(y2,'\n')
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)
print(y3,'\n')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [55]:
# element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
print(z1,'\n')
z2 = tensor.mul(tensor)
print(z2,'\n')

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out = z3)
print(z3,'\n')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



**Single-element tensors**: Converting single element tensor to numerical value

In [61]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**In place operation**:


*   Operations that store the result into the operand are called  in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.
* In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is **discouraged**.




In [64]:
print(f"{tensor}\n ")
tensor.add_(5)
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
 
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


**Bridge with NumPy {#bridge-to-np-label}**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

 # **Tensor to NumPy array**

In [65]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")


t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [67]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


# **NumPy array to Tensor**

In [73]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n:{n}")
print(f"t:{t}")


n:[1. 1. 1. 1. 1.]
t:tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Change in numpy reflects in tensor

In [75]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")


n: [3. 3. 3. 3. 3.]
t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
